### ISSUE TITLE
Fix GUI positioning

### ISSUE THREAD

**Issue by OstGeneralen** [SpaceFarerOrg/SpaceFarer#2]
Current GUI is working and simple, adjustments to position is needed and a few features are still to be added.

- Inertia Dampers (?)
- Radar
- Fuel

![image](https://cloud.githubusercontent.com/assets/2298607/22628829/708ca292-ebdb-11e6-800d-0234d26ad40f.png)

**Comment by Thejokemachine** [comment]
Finfint
